In [3]:
import numpy as np
notre_tableau = np.array({i for i in range(21)})
print(notre_tableau)
type(notre_tableau)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


numpy.ndarray

In [4]:
mon_array_bidimension=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mon_array_bidimension)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#pour selectionne la valeur de la tableau
print(mon_array_bidimension[0][2])
print(mon_array_bidimension[0,2])
#pour selectionne la 1er colonne
print(mon_array_bidimension[:,0])
#pour selectionne la 1er ligne
print(mon_array_bidimension[0,:])

3
3
[1 4 7]
[1 2 3]


In [8]:
#pour selectionne la 1er colonne
mon_array_bidimension[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [9]:
mon_array_bidimension[0,0]=2.5

In [10]:
print(mon_array_bidimension)

[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#affiche de capacité de mémoire
mon_array_bidimension.dtype

dtype('int64')

In [13]:
mon_array_bidimension[0,0]=1
mon_array_bidimension.dtype

dtype('int64')

In [14]:
#define le type de donnees de départ dtype="float"
mon_array_bidimension=np.array([[1.5, 2, 3], [4, 5, 6.7], [7, 8.4, 9]], dtype="float")
print(mon_array_bidimension)
mon_array_bidimension.dtype

[[1.5 2.  3. ]
 [4.  5.  6.7]
 [7.  8.4 9. ]]


dtype('float64')

In [16]:
#np.zeros() permet de creer un ndarray spécifier que  le tableau soit int, soit float
mon_array_zeros=np.zeros((4,6), dtype=int)
print(mon_array_zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
#np.ones() permet de creer un ndarray spécifier que  le tableau soit int, soit float
mon_array_ones=np.ones((4,6), dtype=int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [18]:
#np.randoms() permet de creer un ndarray dont les valeurs s crées aléroitoire
mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.23558564 0.79583025]
 [0.40675394 0.86014862]
 [0.63083638 0.77944914]
 [0.5335349  0.65066979]]


In [21]:
#lire des donnees de fichier
#delimiter=";" skip_header : sauter la 1er ligne comme la tete de fichier
iris=np.genfromtxt("exoPython/Simplon_Dev_IA_2022/exemples/iris.csv", delimiter=";", skip_header=True, encoding="latin-1")
print(iris)
iris.dtype

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

dtype('float64')

In [23]:
np.savetxt("exoPython/Simplon_Dev_IA_2022/exemples/iris2.csv", iris, delimiter=";")