In [3]:
import numpy as np
notre_tableau = np.array({i for i in range(21)})
print(notre_tableau)
type(notre_tableau)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


numpy.ndarray

In [4]:
mon_array_bidimension=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mon_array_bidimension)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#pour selectionne la valeur de la tableau
print(mon_array_bidimension[0][2])
print(mon_array_bidimension[0,2])
#pour selectionne la 1er colonne
print(mon_array_bidimension[:,0])
#pour selectionne la 1er ligne
print(mon_array_bidimension[0,:])

3
3
[1 4 7]
[1 2 3]


In [8]:
#pour selectionne la 1er colonne
mon_array_bidimension[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [9]:
mon_array_bidimension[0,0]=2.5

In [10]:
print(mon_array_bidimension)

[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#affiche de capacité de mémoire
mon_array_bidimension.dtype

dtype('int64')

In [13]:
mon_array_bidimension[0,0]=1
mon_array_bidimension.dtype

dtype('int64')

In [14]:
#define le type de donnees de départ dtype="float"
mon_array_bidimension=np.array([[1.5, 2, 3], [4, 5, 6.7], [7, 8.4, 9]], dtype="float")
print(mon_array_bidimension)
mon_array_bidimension.dtype

[[1.5 2.  3. ]
 [4.  5.  6.7]
 [7.  8.4 9. ]]


dtype('float64')

In [16]:
#np.zeros() permet de creer un ndarray spécifier que  le tableau soit int, soit float
mon_array_zeros=np.zeros((4,6), dtype=int)
print(mon_array_zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
#np.ones() permet de creer un ndarray spécifier que  le tableau soit int, soit float
mon_array_ones=np.ones((4,6), dtype=int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [18]:
#np.randoms() permet de creer un ndarray dont les valeurs s crées aléroitoire
mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.23558564 0.79583025]
 [0.40675394 0.86014862]
 [0.63083638 0.77944914]
 [0.5335349  0.65066979]]


In [26]:
#lire des donnees de fichier
#delimiter=";" skip_header : sauter la 1er ligne comme la tete de fichier
iris=np.genfromtxt("exoPython/Simplon_Dev_IA_2022/exemples/iris.csv", delimiter=";", skip_header=True, encoding="latin-1")
print(iris)
iris.dtype

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

dtype('float64')

In [23]:
np.savetxt("exoPython/Simplon_Devi_IA_2022/exemples/iris2.csv", iris, delimiter=";")

In [32]:
%pwd


'/home/simplon'

In [33]:
type(iris)

numpy.ndarray

In [34]:
print(iris[2,1])

3.2


In [35]:
iris[iris>2].shape[0]

472

In [36]:
iris>2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [46]:
#filtre des lignes dont la valeur du colonne 3 > 5
iris_bis = iris[iris[:,4]==3]
iris_bis

array([[6.3, 3.3, 6. , 2.5, 3. ],
       [5.8, 2.7, 5.1, 1.9, 3. ],
       [7.1, 3. , 5.9, 2.1, 3. ],
       [6.3, 2.9, 5.6, 1.8, 3. ],
       [6.5, 3. , 5.8, 2.2, 3. ],
       [7.6, 3. , 6.6, 2.1, 3. ],
       [4.9, 2.5, 4.5, 1.7, 3. ],
       [7.3, 2.9, 6.3, 1.8, 3. ],
       [6.7, 2.5, 5.8, 1.8, 3. ],
       [7.2, 3.6, 6.1, 2.5, 3. ],
       [6.5, 3.2, 5.1, 2. , 3. ],
       [6.4, 2.7, 5.3, 1.9, 3. ],
       [6.8, 3. , 5.5, 2.1, 3. ],
       [5.7, 2.5, 5. , 2. , 3. ],
       [5.8, 2.8, 5.1, 2.4, 3. ],
       [6.4, 3.2, 5.3, 2.3, 3. ],
       [6.5, 3. , 5.5, 1.8, 3. ],
       [7.7, 3.8, 6.7, 2.2, 3. ],
       [7.7, 2.6, 6.9, 2.3, 3. ],
       [6. , 2.2, 5. , 1.5, 3. ],
       [6.9, 3.2, 5.7, 2.3, 3. ],
       [5.6, 2.8, 4.9, 2. , 3. ],
       [7.7, 2.8, 6.7, 2. , 3. ],
       [6.3, 2.7, 4.9, 1.8, 3. ],
       [6.7, 3.3, 5.7, 2.1, 3. ],
       [7.2, 3.2, 6. , 1.8, 3. ],
       [6.2, 2.8, 4.8, 1.8, 3. ],
       [6.1, 3. , 4.9, 1.8, 3. ],
       [6.4, 2.8, 5.6, 2.1, 3. ],
       [7.2, 3

In [38]:
#select que colonne 0
iris[:,0]    

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [47]:
%pwd


'/home/simplon'

In [49]:
%pwd

'/home/simplon'

In [61]:
#fancy indexing
notre_tableau=np.array([i for i in range(1,21)])
print("Mon tableau")
print(notre_tableau)
print("apres fancy indexing")
indices=np.array([[4,10,5],[12,8,9], [6,14,15]])
print(notre_tableau[indices])
print(notre_tableau)

Mon tableau
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
apres fancy indexing
[[ 5 11  6]
 [13  9 10]
 [ 7 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
#BUT: donner un tableau d'index
A = notre_tableau[indices]
print(A[0,2])
print(A[2,2])

6
16


In [65]:
#3 premier element 
notre_tableau[:3]

array([1, 2, 3])

In [66]:
#10 dernier éléments à partir de l'index 10
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
notre_tableau[3:7]

array([4, 5, 6, 7])

In [69]:
#tous les éléments avec un pas de deux, entre 3:8
notre_tableau[3:8:2]
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [70]:
#selectionne les 2 première lignes des 4 colonne
iris[:2, :4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [72]:
iris[145:, 2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [73]:
#première ligne et tous les colonnes
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [75]:
#premier colonne s/tous les lignes
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [76]:
#derniere ligne
iris[-1, :]

array([5.9, 3. , 5.1, 1.8, 3. ])

In [77]:
#creer sous_tableau de 5 premier ele de notre_tableau
#creer une vue s/notre_tableau
sous_tableau=notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [78]:
sous_tableau[0] = 10
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
sous_tableau2=notre_tableau[:5].copy()
sous_tableau[0]=1
print("notre_tableau = ",notre_tableau)
print("sous_tableau = ",sous_tableau)
print("sous_tableau2 = ",sous_tableau2)

notre_tableau =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
sous_tableau =  [1 2 3 4 5]
sous_tableau2 =  [100   2   3   4   5]


In [89]:
np.add(notre_tableau,10)
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
import numpy as np
m_t=np.array([[10,11,12],[13,14,15],[16,17,18]])
m_t


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [93]:
a=np.add(m_t,10)
a
m_t

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [95]:
m=np.multiply(m_t, 20)
m
m_t

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [96]:
m_t2=np.array([10,20,30])
m_t2

array([10, 20, 30])

In [98]:
s=np.subtract(m_t, m_t2)
s

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [100]:
tableau3=np.array([[1,2,3],[4,5,6], [7,8,9]])
tableau3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
#aggréation == GROUPBY
print("Somme /l'ensemble des ele: ")
print(np.sum(iris))

#axis = 0 : effectue le calcul p/colonne
print("Somme s/colonne")
print(np.sum(iris, axis=0))
print("Somme s/ligne")
print(np.sum(iris, axis=1)) #s/ligne

Somme /l'ensemble des ele: 
2378.7
Somme s/colonne
[876.5 458.6 563.7 179.9 300. ]
Somme s/ligne
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [108]:
print("Moyenne :\n", np.mean(iris, axis=0))
print("Variant avec moyenne :\n", np.std(iris, axis=0))

Moyenne :
 [5.84333333 3.05733333 3.758      1.19933333 2.        ]
Variant avec moyenne :
 [0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [111]:
print("Max par colonne:\n", np.max(iris, axis=0))


Max par colonne:
 [7.9 4.4 6.9 2.5 3. ]


In [125]:
#select tous les lignes, que le colonne 5 (dernier colonne)
iris[:,4]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [122]:
#vue qui contienne tous les lignes dont la valeur en 5e colonne = 3
#creer une vue des lignes dont le type (colonne 5) = 1 ou 2 ou 3
#faire un masque par un teste iris[:,4]==?
iris3 = iris[iris[:,4]==3] 
iris2 = iris[iris[:,4]==2]
iris1 = iris[iris[:,4]==1]
#print(iris3)
print("Moyenne par colonnes \n Type 3 = ",np.mean(iris3, axis=0))
print(" Type 2 = ",np.mean(iris2, axis=0))
print(" Type 1 = ",np.mean(iris1, axis=0))

Moyenne par colonnes 
 Type 3 =  [6.588 2.974 5.552 2.026 3.   ]
 Type 2 =  [5.936 2.77  4.26  1.326 2.   ]
 Type 1 =  [5.006 3.428 1.462 0.246 1.   ]


In [132]:
print("Size de table : ", np.size(iris))
print("Shape de table : ", np.shape(iris))

Size de table :  750
Size de table :  (150, 5)


In [133]:
np.append(notre_tableau,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [134]:
np.append(iris,[[10,10,10,10,10]], axis = 0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [135]:
np.insert(notre_tableau,1,42)

array([ 1, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [136]:
np.insert(notre_tableau,1,[42,43,44,45,46])

array([ 1, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [137]:
np.insert(iris, 1, [10,10,10,10,3], axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. ,  3. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [138]:
#supprime une colonne, les eles de tableau , s/vue
np.delete(iris, 1, axis=1)

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [140]:
np.delete(notre_tableau,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [141]:
#split : separe le tableau
notre_tableau


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [144]:
tab1, tab2, tab3, tab4 = np.split(notre_tableau, [2,8,15])
print("tab1 = ", tab1)
print("tab2 = ", tab2)
print("tab3 = ", tab3)
print("tab4 = ", tab4)

tab1 =  [1 2]
tab2 =  [3 4 5 6 7 8]
tab3 =  [ 9 10 11 12 13 14 15]
tab4 =  [16 17 18 19 20]


In [146]:
my_array = np.array([[2,5,6],[9,10,11],[5,9,15]])
print("avant division")
print(my_array)
array1, array2 = np.vsplit(my_array, [2])
print("Resultat division vertical")
print("a1 = ", array1)
print("a2 = ",array2)

avant division
[[ 2  5  6]
 [ 9 10 11]
 [ 5  9 15]]
Resultat division vertical
a1 =  [[ 2  5  6]
 [ 9 10 11]]
a2 =  [[ 5  9 15]]


In [147]:
array3, array4 = np.hsplit(my_array, [1])
print("Resultat division vertical")
print("a3 = ", array3)
print("a4 = ",array4)

Resultat division vertical
a1 =  [[2]
 [9]
 [5]]
a2 =  [[ 5  6]
 [10 11]
 [ 9 15]]


In [148]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6, 7, 8, 9])
print(arr1)
print(arr2)
np.concatenate([arr1, arr2])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
arr3 = np.array([[1,2,3],[4,5,8]], dtype="float")
arr4 = np.array([[6, 7, 8],[9,10,11]], dtype="float")
print(arr3)
print(arr4)
np.concatenate([arr3, arr4])

[[1. 2. 3.]
 [4. 5. 8.]]
[[ 6.  7.  8.]
 [ 9. 10. 11.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  8.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [158]:
arr5 = np.array([[11,12,13],[14,5,18],[0,5,18]], dtype="float")
np.concatenate([arr3, arr4, arr5])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  8.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [11., 12., 13.],
       [14.,  5., 18.],
       [ 0.,  5., 18.]])

In [193]:
arr6 = np.array([11,11,11])
arr7 = np.array([10,110,110])
print(arr5)
print("----")
print(arr6)
print("----")
print("concat vertical, ajout des lignes")
np.vstack([arr5, arr6])
print("----")
print("concat horizon, ajout des COLONNES")
np.hstack((arr5, arr7))

[[11. 12. 13.]
 [14.  5. 18.]
 [ 0.  5. 18.]]
----
[11 11 11]
----
concat vertical, ajout des lignes
----
concat horizon, ajout des COLONNES


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [191]:
#t1,t2=np.hsplit(iris,[4])
t1=np.delete(iris,4, axis=1)
moyen=np.mean(t1,axis=1)
np.insert(iris,5,moyen, axis=1)


array([[5.1  , 3.5  , 1.4  , 0.2  , 1.   , 2.55 ],
       [4.9  , 3.   , 1.4  , 0.2  , 1.   , 2.375],
       [4.7  , 3.2  , 1.3  , 0.2  , 1.   , 2.35 ],
       [4.6  , 3.1  , 1.5  , 0.2  , 1.   , 2.35 ],
       [5.   , 3.6  , 1.4  , 0.2  , 1.   , 2.55 ],
       [5.4  , 3.9  , 1.7  , 0.4  , 1.   , 2.85 ],
       [4.6  , 3.4  , 1.4  , 0.3  , 1.   , 2.425],
       [5.   , 3.4  , 1.5  , 0.2  , 1.   , 2.525],
       [4.4  , 2.9  , 1.4  , 0.2  , 1.   , 2.225],
       [4.9  , 3.1  , 1.5  , 0.1  , 1.   , 2.4  ],
       [5.4  , 3.7  , 1.5  , 0.2  , 1.   , 2.7  ],
       [4.8  , 3.4  , 1.6  , 0.2  , 1.   , 2.5  ],
       [4.8  , 3.   , 1.4  , 0.1  , 1.   , 2.325],
       [4.3  , 3.   , 1.1  , 0.1  , 1.   , 2.125],
       [5.8  , 4.   , 1.2  , 0.2  , 1.   , 2.8  ],
       [5.7  , 4.4  , 1.5  , 0.4  , 1.   , 3.   ],
       [5.4  , 3.9  , 1.3  , 0.4  , 1.   , 2.75 ],
       [5.1  , 3.5  , 1.4  , 0.3  , 1.   , 2.575],
       [5.7  , 3.8  , 1.7  , 0.3  , 1.   , 2.875],
       [5.1  , 3.8  , 1.5  , 0.

In [188]:
np.hstack([iris, np.reshape(np.mean(iris[:,0:4], axis=1), (-1, 1))])

array([[5.1  , 3.5  , 1.4  , 0.2  , 1.   , 2.55 ],
       [4.9  , 3.   , 1.4  , 0.2  , 1.   , 2.375],
       [4.7  , 3.2  , 1.3  , 0.2  , 1.   , 2.35 ],
       [4.6  , 3.1  , 1.5  , 0.2  , 1.   , 2.35 ],
       [5.   , 3.6  , 1.4  , 0.2  , 1.   , 2.55 ],
       [5.4  , 3.9  , 1.7  , 0.4  , 1.   , 2.85 ],
       [4.6  , 3.4  , 1.4  , 0.3  , 1.   , 2.425],
       [5.   , 3.4  , 1.5  , 0.2  , 1.   , 2.525],
       [4.4  , 2.9  , 1.4  , 0.2  , 1.   , 2.225],
       [4.9  , 3.1  , 1.5  , 0.1  , 1.   , 2.4  ],
       [5.4  , 3.7  , 1.5  , 0.2  , 1.   , 2.7  ],
       [4.8  , 3.4  , 1.6  , 0.2  , 1.   , 2.5  ],
       [4.8  , 3.   , 1.4  , 0.1  , 1.   , 2.325],
       [4.3  , 3.   , 1.1  , 0.1  , 1.   , 2.125],
       [5.8  , 4.   , 1.2  , 0.2  , 1.   , 2.8  ],
       [5.7  , 4.4  , 1.5  , 0.4  , 1.   , 3.   ],
       [5.4  , 3.9  , 1.3  , 0.4  , 1.   , 2.75 ],
       [5.1  , 3.5  , 1.4  , 0.3  , 1.   , 2.575],
       [5.7  , 3.8  , 1.7  , 0.3  , 1.   , 2.875],
       [5.1  , 3.8  , 1.5  , 0.

In [202]:
moyen = np.mean(iris, axis=0)
np.insert(iris, iris.shape[0], moyen, axis=0)
# np.insert(iris, 0, moyen, axis=0)

array([[5.1       , 3.5       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.        , 1.4       , 0.2       , 1.        ],
       [4.7       , 3.2       , 1.3       , 0.2       , 1.        ],
       [4.6       , 3.1       , 1.5       , 0.2       , 1.        ],
       [5.        , 3.6       , 1.4       , 0.2       , 1.        ],
       [5.4       , 3.9       , 1.7       , 0.4       , 1.        ],
       [4.6       , 3.4       , 1.4       , 0.3       , 1.        ],
       [5.        , 3.4       , 1.5       , 0.2       , 1.        ],
       [4.4       , 2.9       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.1       , 1.5       , 0.1       , 1.        ],
       [5.4       , 3.7       , 1.5       , 0.2       , 1.        ],
       [4.8       , 3.4       , 1.6       , 0.2       , 1.        ],
       [4.8       , 3.        , 1.4       , 0.1       , 1.        ],
       [4.3       , 3.        , 1.1       , 0.1       , 1.        ],
       [5.8       , 4.        , 1.